In [1]:
import numpy as np
import numba as nb
from numba.typed import List
import pandas as pd
import itertools
from operator import itemgetter
import gc

from scipy.stats import norm, lognorm, truncnorm
import matplotlib.pyplot as plt
import seaborn as sns

from collections import Counter, deque
from sys import getsizeof

In [2]:
from sedgen.initialization import SedGen
from sedgen import initialization as ini
from sedgen import general as gen
from sedgen import preprocessing

In [15]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
# Load jupyter extension to reload packages before executing user code.
# https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html
%load_ext autoreload
# Reload all packages (except those excluded by %aimport) every time 
# before executing the Python code typed.
%autoreload 2

In [4]:
par_rock_volumes = [1e9, 1e8, 1e7, 1e6, 1e5, 1e4, 1e3, 1e2, 1e1]
minerals = ["Q", "P", "K", "B", "O", "A"]
par_rock_volume = 1000000


In [5]:
modal_mineralogy = np.array([0.30591989, 0.38159713, 0.26209888, 0.0188256 , 0.00799247, 0.02356603])

In [6]:
csds_CA_NS_means = np.array([0.309, 0.330, 0.244, 0.223, 0.120, 0.122])
csds_CA_NS_stds = np.array([0.823, 0.683, 0.817, 0.819, 0.554, 0.782])

In [7]:
sedgentest = SedGen(minerals, par_rock_volume, modal_mineralogy, csds_CA_NS_means, csds_CA_NS_stds, learning_rate = 100000, timed = True)

---SedGen model initialization started---

Initializing modal mineralogy...
Initializing csds...
Initializing bins...
Simulating mineral occurences... |Q|P|K|B|O|A| Done in 0.9646 seconds
Initializing interfaces... |Q|P|K|B|O|A| Done in 1.3544 seconds
Counting interfaces...  Done in 0.0001 seconds
Correcting interface arrays for consistency...
too much Q 1
all good P 0
all good K 0
too much B 1
too few O -1
too few A -1
Initializing crystal size array... |Q|P|K|B|O|A| Done in 0.0028 seconds
Initializing inter-crystal breakage probability arrays...
Initializing model evolution arrays...
Initializing discretization for model's weathering...

---SedGen model initialization finished succesfully---


In [8]:
sedgentest.simulated_volume

array([306018.91791864, 384310.67218782, 262246.36236315,  29009.83767258,
        12319.11069192,  23599.20754296])

In [9]:
sedgen_CA_NS_list = []
for i in range (len(par_rock_volumes)):
    print(par_rock_volumes[i])
    sedgen_CA_NS = SedGen (minerals, par_rock_volumes[i], modal_mineralogy, csds_CA_NS_means, csds_CA_NS_stds, learning_rate=10000, timed = False)
    sedgen_CA_NS_list.append(sedgen_CA_NS)
    

#now the model should have ran 9 times for different parent rock volumes, and the variable 'sedgen_CA_NS_list' should contain the output
#

1000000000.0
---SedGen model initialization started---

Initializing modal mineralogy...
Initializing csds...
Initializing bins...
Simulating mineral occurences... |Q|P|K|B|O|A|
Initializing interfaces... |Q|P|K|B|O|A|
Counting interfaces...
Correcting interface arrays for consistency...
too much Q 4
too few P -2
too few K -1
all good B 0
all good O 0
too few A -1
Initializing crystal size array... |Q|P|K|B|O|A|
Initializing inter-crystal breakage probability arrays...
Initializing model evolution arrays...
Initializing discretization for model's weathering...

---SedGen model initialization finished succesfully---
100000000.0
---SedGen model initialization started---

Initializing modal mineralogy...
Initializing csds...
Initializing bins...
Simulating mineral occurences... |Q|P|K|B|O|A|
Initializing interfaces... |Q|P|K|B|O|A|
Counting interfaces...
Correcting interface arrays for consistency...
all good Q 0
all good P 0
all good K 0
too few B -1
all good O 0
too much A 1
Initializin

IndexError: tuple index out of range

In [10]:
par_rock_volumes[0] * modal_mineralogy

array([3.0591989e+08, 3.8159713e+08, 2.6209888e+08, 1.8825600e+07,
       7.9924700e+06, 2.3566030e+07])

In [18]:
np.sum(sedgen_CA_NS_list[0].mcg)
sedgen_CA_NS_list[1].simulated_volume/1e8
np.sum(sedgen_CA_NS_list[1].simulated_volume)

0

array([0.30594789, 0.38160202, 0.26209888, 0.0188263 , 0.0080586 ,
       0.02367934])

100021302.14301005